auth.token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyIiwicm9sZXMiOiJST0xFX1VTRVIsUk9MRV9BRE1JTiIsImlhdCI6MTcyNTA4MjgwNSwiZXhwIjoxNzI1MDg4ODA1LCJhcHBfaWQiOjgxMSwicGVybWlzc2lvbl9pZCI6MTExfQ.chKy0y77Xo_hEWSPVYGh6O-3pjzS2TaB5ukunP1B8ps
grpc:
  client:
    local-grpc-server:
      address: 'static://127.0.0.1:9190'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
