# auth.username: guest
auth.username: user
# auth.username: unknown

grpc:
  client:
    local-grpc-server:
      address: 'static://127.0.0.1:9090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
